[project]
name = "breadwinner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-genai>=1.56.0",
    "pdf2image>=1.17.0",
    "pypdf>=6.5.0",
    "pytesseract>=0.3.13",
]
